const router = require("express").Router();
const verifyToken = require("../middleware/authMiddleware");
const { authorizeRoles } = require("../middleware/roleMiddleware");
const upload = require("../middleware/assessmentMaterialUpload");
const controller = require("../controllers/facultyAssessmentController");
const facultyOnly = [verifyToken, authorizeRoles("faculty")];
router.get("/", facultyOnly, controller.getAssessments);
router.get("/students", facultyOnly, controller.getStudents);
router.post("/extract", facultyOnly, upload, controller.extractMaterial);
router.post("/", facultyOnly, controller.createAssessment);
router.post("/:id/assign", facultyOnly, controller.assignAssessment);
router.get("/:id/details", facultyOnly, controller.getAssessmentDetails);
router.put("/:id/title", facultyOnly, controller.updateAssessmentTitle);
router.delete("/:id", facultyOnly, controller.deleteAssessment);
module.exports = router;
