import { useEffect, useState } from 'react'
import { api } from '../../api'

export default function FacultyAssessments() {
  const [file, setFile] = useState(null), [sourceText, setSourceText] = useState(''), [questions, setQuestions] = useState([]), [students, setStudents] = useState([]), [studentIds, setStudentIds] = useState([]), [title, setTitle] = useState(''), [error, setError] = useState(''), [info, setInfo] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { api.get('/faculty/assessments/students').then(r => r.ok ? setStudents(r.data.data || []) : setError(r.data?.message || 'Unable to load assigned students')) }, [])
  const extract = async () => { if (!file) return setError('Choose a PDF or DOCX document first.'); setBusy(true); const f = new FormData(); f.append('material', file); const r = await api.upload('/faculty/assessments/extract', f); setBusy(false); r.ok ? (setSourceText(r.data.data.text), setInfo('Content extracted. Generate questions for review.')) : setError(r.data?.message || 'Extraction failed') }
  const generate = async () => { setBusy(true); const r = await api.post('/faculty/assessments/generate', { sourceText }); setBusy(false); r.ok ? setQuestions(r.data.data.questions) : setError(r.data?.message || 'Generation failed') }
  const finalize = async () => { setBusy(true); const r = await api.post('/faculty/assessments', { title, questions, studentIds }); setBusy(false); r.ok ? setInfo('Assessment finalized and assigned.') : setError(r.data?.message || 'Finalization failed') }
  return <><div className="page-title"><div><h1>Assessments</h1><div className="subtitle">Upload material, review AI questions, and assign students.</div></div></div>{error && <div className="alert error">{error}</div>}{info && <div className="alert success">{info}</div>}<div className="card"><h3>1. Upload learning material</h3><input type="file" accept=".pdf,.doc,.docx" onChange={e => setFile(e.target.files?.[0])}/><button className="btn mt" disabled={busy} onClick={extract}>Extract content</button>{sourceText && <button className="btn secondary mt" disabled={busy} onClick={generate}>Generate questions</button>}</div>{questions.length > 0 && <div className="card mt"><h3>2. Review and assign</h3><div className="form-group"><label>Title</label><input value={title} onChange={e => setTitle(e.target.value)}/></div>{questions.map((q, i) => <div className="card mb" key={i}><textarea value={q.question} onChange={e => setQuestions(items => items.map((x, j) => j === i ? { ...x, question: e.target.value } : x))}/><p className="mt">{q.options.join(' · ')}</p><button className="btn small danger mt" onClick={() => setQuestions(items => items.filter((_, j) => j !== i))}>Delete</button></div>)}<div className="form-group"><label>Assigned students</label><select multiple value={studentIds} onChange={e => setStudentIds(Array.from(e.target.selectedOptions, o => o.value))}>{students.map(s => <option value={s._id} key={s._id}>{s.name} ({s.email})</option>)}</select></div><button className="btn" disabled={busy || !title || !studentIds.length} onClick={finalize}>Finalize and assign</button></div>}</>
}
